name = "yaftree"
version = "0.1.0"
license = "BSD 3-clause"
author = "Dominik Gronkiewicz"
maintainer = "gronki@gmail.com"
copyright = "Copyright 2024, Dominik Gronkiewicz"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = true
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

